### PR TITLE
Poem german

### PR DESCRIPTION
**Pull request by arc18**
Made a german translation.

### CODE REVIEW

**Comment by RainbowCoder** [comment]
I think it might be better to have the German version be in a separate file like `poem_deutsch.txt`?  I can help with creating the file or offer any tips!

**Comment by arc18** [comment]
I can't see how to create a seperate file like poem-german.txt. Any tips?

**Comment by arc18** [comment]
I can't see how to create a separate file like poem-german.txt. Any tips?

**Comment by shiffman** [comment]
Glad to see you figured it out, nice work!

**Pull request closed without merging**
